<?php

/**
 * Installer Config File
 * 
 *!!! Please do not edit this file !!!
 * 
 * @author    patrick115 <info@patrick115.eu>
 * @copyright ©2019
 * @link      https://github.com/patrick11514
 * @version   0.0.1
 * 
 */

$install = [
    1 => "Database",
    2 => "Bot",
    3 => "SSH"
];

$source = [
    1 => "/src/installer/part_1.html",
    2 => "/src/installer/part_2.html",
    3 => "/src/installer/part_3.html",
];